### ISSUE TITLE
Redo UI in Vue

### ISSUE THREAD

**Issue by StruckCroissant** [StruckCroissant/Game-DB#54]
After working with Vue for a bit I feel that using the framework for this project would work better for a couple different reasons:
1. The simplicity of Vue allows for faster development. (plus I have more experience in it)
   1. Can leverage the composition API to more effectively organize front-end code
1. Vue integrates seamlessly with tools like Vite for faster build & load times. Plus there is a rich 3rd-party ecosystem that will prove useful

## TODO
- [x] Add Vue to project
- Add auxillary libraries
   - [x] Import and integrate with Vite
   - [x] Add VueUse
   - [x] Add Vuetify
   - [x] Look into VueX/routing
- Refactor existing pages
   - [x] Login/registration page (commandeering #40)
   - [x] #64

**Comment by StruckCroissant** [comment]
Angular UI has been fully updated to Vue. Closing.
